name: Build and Deploy to GAE

on:
  push:
    branches:
      - master
      - fix/deployment-environment

jobs:
  deploy:
    name: Deploy to GAE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          deliverables: "app.yaml"
          working_directory: "./"
        env:
          DB_USERNAME: ${{ secrets.DB_USER_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_CONNECTION_NAME: ${{ secrets.DB_CONNECTION_NAME }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          SIGNING_SALT: ${{ secrets.SIGNING_SALT }}
