name: Build and Deploy to GAE

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to GAE
    steps:
      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}